import 'package:cloud_firestore/cloud_firestore.dart';

// Esta lista es tu BASE DE DATOS MAESTRA.
// Aquí irás agregando los 300 jugadores poco a poco.
final List<Map<String, dynamic>> initialPlayers = [
  {
    "name": "Lionel Messi PRIME",
    "position": "EXD",
    "rating": 100,
    "team": "Barcelona",
    "tier": "PRIME",
    "photoUrl": "",
    "age": 25,
  },
  {
    "name": "Neymar Jr PRIME",
    "position": "EXI",
    "rating": 96,
    "team": "Barcelona",
    "tier": "PRIME",
    "photoUrl": "",
    "age": 23,
  },
  {
    "name": "Luka Modric PRIME",
    "position": "MC",
    "rating": 94,
    "team": "Real Madrid",
    "tier": "PRIME",
    "photoUrl": "",
    "age": 33,
  },
  {
    "name": "Casemiro PRIME",
    "position": "MCD",
    "rating": 92,
    "team": "Real Madrid",
    "tier": "PRIME",
    "photoUrl": "",
    "age": 27,
  },
  {
    "name": "Dani ALbes PRIME",
    "position": "LD",
    "rating": 94,
    "team": "Barcelona",
    "tier": "PRIME",
    "photoUrl": "",
    "age": 28,
  },
  {
    "name": "Marcelo PRIME",
    "position": "LI",
    "rating": 93,
    "team": "Real Madrid",
    "tier": "PRIME",
    "photoUrl": "",
    "age": 29,
  },
  {
    "name": "Virgil van Dijk PRIME",
    "position": "DEC",
    "rating": 94,
    "team": "Liverpool",
    "tier": "PRIME",
    "photoUrl": "",
    "age": 28,
  },
  {
    "name": "Sergio Ramos PRIME",
    "position": "DEC",
    "rating": 93,
    "team": "Real Madrid",
    "tier": "PRIME",
    "photoUrl": "",
    "age": 30,
  },
  {
    "name": "Cristiano Ronaldo PRIME",
    "position": "CD",
    "rating": 98,
    "team": "Real Madrid",
    "tier": "PRIME",
    "photoUrl": "",
    "age": 32,
  },
  {
    "name": "Neuer PRIME",
    "position": "PO",
    "rating": 95,
    "team": "Bayer Munich",
    "tier": "PRIME",
    "photoUrl": "",
    "age": 28,
  },
  {
    "name": "Cafu",
    "position": "LD",
    "rating": 93,
    "team": "AS Roma",
    "tier": "LEYENDA",
    "photoUrl": "",
    "age": 30,
  },
  {
    "name": "Lev Yashin",
    "position": "PO",
    "rating": 95,
    "team": "Dinamo Moscu",
    "tier": "LEYENDA",
    "photoUrl": "",
    "age": 26,
  },
  {
    "name": "Paolo Maldini",
    "position": "DEC",
    "rating": 97,
    "team": "AC Milan",
    "tier": "LEYENDA",
    "photoUrl": "",
    "age": 25,
  },
  {
    "name": "Franco Baresi",
    "position": "DEC",
    "rating": 96,
    "team": "AC Milan",
    "tier": "LEYENDA",
    "photoUrl": "",
    "age": 28,
  },
  {
    "name": "Roberto Carlos",
    "position": "LI",
    "rating": 94,
    "team": "Real Madrid",
    "tier": "LEYENDA",
    "photoUrl": "",
    "age": 27,
  },
  {
    "name": "Xavi Hernandez",
    "position": "MCD",
    "rating": 96,
    "team": "Barcelona",
    "tier": "LEYENDA",
    "photoUrl": "",
    "age": 31,
  },
  {
    "name": "Zinedin Zidane",
    "position": "MC",
    "rating": 96,
    "team": "Real Madrid",
    "tier": "LEYENDA",
    "photoUrl": "",
    "age": 29,
  },
  {
    "name": "Johan Cruyff",
    "position": "MO",
    "rating": 98,
    "team": "Barcelona",
    "tier": "LEYENDA",
    "photoUrl": "",
    "age": 27,
  },
  {
    "name": "Ronaldinho",
    "position": "EXI",
    "rating": 97,
    "team": "Barcelona",
    "tier": "LEYENDA",
    "photoUrl": "",
    "age": 25,
  },
  {
    "name": "Pele",
    "position": "CD",
    "rating": 99,
    "team": "Santos FC",
    "tier": "LEYENDA",
    "photoUrl": "",
    "age": 24,
  },
  {
    "name": "Diego Maradona",
    "position": "EXI",
    "rating": 99,
    "team": "Napoli",
    "tier": "LEYENDA",
    "photoUrl": "",
    "age": 25,
  },
  {
    "name": "Kylian Mbappé",
    "position": "CD",
    "rating": 89,
    "team": "Real Madrid",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 27,
  },
  {
    "name": "Erling Haaland",
    "position": "CD",
    "rating": 88,
    "team": "Manchester City",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 24,
  },
  {
    "name": "Kevin De Bruyne PRIME",
    "position": "MO",
    "rating": 95,
    "team": "Manchester City",
    "tier": "PRIME",
    "photoUrl": "",
    "age": 29,
  },
  {
    "name": "Harry Kane",
    "position": "CD",
    "rating": 88,
    "team": "Bayer Munich",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 32,
  },
  {
    "name": "Ousmane Dembélé",
    "position": "CD",
    "rating": 87,
    "team": "PSG",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 28,
  },
  {
    "name": "Karim Benzema",
    "position": "CD",
    "rating": 87,
    "team": "Al Ittihad Club",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 37,
  },
  {
    "name": "Alexander Isak",
    "position": "CD",
    "rating": 86,
    "team": "Liverpool",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 26,
  },
  {
    "name": "Robert Lewandowski",
    "position": "CD",
    "rating": 86,
    "team": "Barcelona",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 37,
  },
  {
    "name": "Julian Alvarez",
    "position": "CD",
    "rating": 86,
    "team": "Atletico Madrid",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 25,
  },
  {
    "name": "Lautaro Martínez",
    "position": "CD",
    "rating": 85,
    "team": "Inter Milan",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 28,
  },
  {
    "name": "Antoine Griezmann",
    "position": "SD",
    "rating": 85,
    "team": "Atletico Madrid",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 34,
  },
  {
    "name": "Neymar Jr",
    "position": "SD",
    "rating": 85,
    "team": "Santos FC",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 33,
  },
  {
    "name": "Serhou Guirassy",
    "position": "CD",
    "rating": 85,
    "team": "Borussia Dortmund",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 29,
  },
  {
    "name": "Victor Osimhen",
    "position": "CD",
    "rating": 85,
    "team": "Galatasaray SK",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 27,
  },
  {
    "name": "Cristiano Ronaldo",
    "position": "CD",
    "rating": 85,
    "team": "Al Nassr FC",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 40,
  },
  {
    "name": "Viktor Gyokeres",
    "position": "CD",
    "rating": 84,
    "team": "Arsenal FC",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 27,
  },
  {
    "name": "Paulo Dybala",
    "position": "SD",
    "rating": 84,
    "team": "AS Roma",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 32,
  },
  {
    "name": "Benjamin Sesko",
    "position": "CD",
    "rating": 83,
    "team": "Manchester United",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 22,
  },
  {
    "name": "Kolo Muani",
    "position": "CD",
    "rating": 83,
    "team": "Tottenham Hotspur",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 27,
  },
  {
    "name": "Ademola Lookman",
    "position": "SD",
    "rating": 83,
    "team": "Atalanta",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 28,
  },
  {
    "name": "Luis Suarez",
    "position": "CD",
    "rating": 82,
    "team": "Inter Miami",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 38,
  },
  {
    "name": "Endrick Felipe",
    "position": "CD",
    "rating": 80,
    "team": "Real Madrid",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 19,
  },
  {
    "name": "Gonzalo Garcia",
    "position": "CD",
    "rating": 75,
    "team": "Real Madrid",
    "tier": "SILVER",
    "photoUrl": "",
    "age": 21,
  },
  {
    "name": "Facundo Colidio",
    "position": "CD",
    "rating": 81,
    "team": "River Plate",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 25,
  },
  {
    "name": "Miguel Borja",
    "position": "CD",
    "rating": 80,
    "team": "River Plate",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 32,
  },
  {
    "name": "Miguel Merentiel",
    "position": "CD",
    "rating": 81,
    "team": "Boca Juniors",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 29,
  },
  {
    "name": "Edinson Cavani",
    "position": "CD",
    "rating": 80,
    "team": "Boca Juniors",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 38,
  },
  {
    "name": "Vinicius Junior",
    "position": "EXI",
    "rating": 89,
    "team": "Real Madrid",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 25,
  },
  {
    "name": "Raphinha",
    "position": "EXI",
    "rating": 88,
    "team": "Barcelona",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 29,
  },
  {
    "name": "Kvaratskhelia",
    "position": "EXI",
    "rating": 86,
    "team": "PSG",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 24,
  },
  {
    "name": "Rafael Leao",
    "position": "EXI",
    "rating": 85,
    "team": "AC Milan",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 26,
  },
  {
    "name": "Nico Williams",
    "position": "EXI",
    "rating": 85,
    "team": "Athletic Bilbao",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 23,
  },
  {
    "name": "Luiz Diaz",
    "position": "EXI",
    "rating": 85,
    "team": "Bayer Munich",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 28,
  },
  {
    "name": "Cody Gakpo",
    "position": "EXI",
    "rating": 84,
    "team": "Liverpool",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 26,
  },
  {
    "name": "Jeremy Doku",
    "position": "EXI",
    "rating": 84,
    "team": "Manchester City",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 22,
  },
  {
    "name": "Savinho",
    "position": "EXI",
    "rating": 84,
    "team": "Manchester City",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 20,
  },
  {
    "name": "Christian Pulisic",
    "position": "EXI",
    "rating": 84,
    "team": "AC Milan",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 27,
  },
  {
    "name": "Barcola",
    "position": "EXI",
    "rating": 84,
    "team": "PSG",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 23,
  },
  {
    "name": "Son Heung-min",
    "position": "EXI",
    "rating": 84,
    "team": "Los Angeles FC",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 33,
  },
  {
    "name": "Sadio Mane",
    "position": "EXI",
    "rating": 84,
    "team": "Al Nassr",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 32,
  },
  {
    "name": "Gabriel Martinelli",
    "position": "EXI",
    "rating": 83,
    "team": "Arsenal FC",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 24,
  },
  {
    "name": "Federico Dimarco",
    "position": "MDI",
    "rating": 83,
    "team": "Inter Milan",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 28,
  },
  {
    "name": "Ferran Torres",
    "position": "EXI",
    "rating": 83,
    "team": "Barcelona",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 24,
  },
  {
    "name": "Joao Felix",
    "position": "EXI",
    "rating": 83,
    "team": "Al Nassr",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 25,
  },
  {
    "name": "Marcus Rashford",
    "position": "EXI",
    "rating": 82,
    "team": "Barcelona",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 28,
  },
  {
    "name": "Martin Terrier",
    "position": "EXI",
    "rating": 82,
    "team": "Bayer Leverkusen",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 82,
  },
  {
    "name": "Alejandro Garnacho",
    "position": "EXI",
    "rating": 81,
    "team": "Chelsea",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 21,
  },
  {
    "name": "Federico Chiesa",
    "position": "EXI",
    "rating": 81,
    "team": "Liverpool",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 28,
  },
  {
    "name": "Ansu Fati",
    "position": "EXI",
    "rating": 80,
    "team": "AS Monaco",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 23,
  },
  {
    "name": "Bryan Gil",
    "position": "EXI",
    "rating": 79,
    "team": "Girona FC",
    "tier": "SILVER",
    "photoUrl": "",
    "age": 23,
  },
  {
    "name": "Arnaut Danjuma",
    "position": "EXI",
    "rating": 79,
    "team": "Valencia CF",
    "tier": "SILVER",
    "photoUrl": "",
    "age": 28,
  },
  {
    "name": "Mohamed Salah",
    "position": "EXD",
    "rating": 88,
    "team": "Liverpool",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 33,
  },
  {
    "name": "Bukayo Saka",
    "position": "EXD",
    "rating": 87,
    "team": "",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 24,
  },
  {
    "name": "Lamine Yamal",
    "position": "EXD",
    "rating": 87,
    "team": "Barcelona",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 18,
  },
  {
    "name": "Lionel Messi",
    "position": "EXD",
    "rating": 87,
    "team": "Inter Miami",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 38,
  },
  {
    "name": "Phil Foden",
    "position": "EXD",
    "rating": 86,
    "team": "Manchester City",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 24,
  },
  {
    "name": "Michael Olise",
    "position": "EXD",
    "rating": 86,
    "team": "Bayer Munich",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 24,
  },
  {
    "name": "Rodrygo",
    "position": "EXD",
    "rating": 85,
    "team": "Real Madrid",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 24,
  },
  {
    "name": "Desire Doue",
    "position": "EXD",
    "rating": 84,
    "team": "PSG",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 20,
  },
  {
    "name": "Leroy Sane",
    "position": "EXD",
    "rating": 84,
    "team": "Galatasaray SK",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 29,
  },
  {
    "name": "Pedro Neto",
    "position": "EXD",
    "rating": 83,
    "team": "Chelsea",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 25,
  },
  {
    "name": "Iñaki Williams",
    "position": "EXD",
    "rating": 83,
    "team": "Athletic Bilbao",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 31,
  },
  {
    "name": "Takefusa Kubo",
    "position": "MDD",
    "rating": 83,
    "team": "Real Sociedad",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 24,
  },
  {
    "name": "Angel Correa",
    "position": "EXD",
    "rating": 83,
    "team": "Tigres UANL",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 29,
  },
  {
    "name": "Denzel Dumfries",
    "position": "MDD",
    "rating": 82,
    "team": "Inter Milan",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 29,
  },
  {
    "name": "Juan Cuadrado",
    "position": "MDD",
    "rating": 82,
    "team": "Pisa Sporting Club",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 37,
  },
  {
    "name": "Matias Soule",
    "position": "EXD",
    "rating": 82,
    "team": "AS Roma",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 22,
  },
  {
    "name": "Giuliano Simeone",
    "position": "MDD",
    "rating": 82,
    "team": "Atletico Madrid",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 23,
  },
  {
    "name": "Nicolas Gonzales",
    "position": "EXD",
    "rating": 82,
    "team": "Atletico Madrid",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 27,
  },
  {
    "name": "Lee Kang-In",
    "position": "EXD",
    "rating": 82,
    "team": "PSG",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 24,
  },
  {
    "name": "Karim Adeyemi",
    "position": "EXD",
    "rating": 82,
    "team": "Borussia Dortmund",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 23,
  },
  {
    "name": "Antony Matheus",
    "position": "EXD",
    "rating": 81,
    "team": "Real Betis",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 25,
  },
  {
    "name": "Franco Mastantuono",
    "position": "EXD",
    "rating": 81,
    "team": "Real Madrid",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 18,
  },
  {
    "name": "Kevin Zenon",
    "position": "MDI",
    "rating": 80,
    "team": "Boca Juniors",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 24,
  },
  {
    "name": "Angel Di Maria",
    "position": "EXD",
    "rating": 80,
    "team": "Rosario Central",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 37,
  },
  {
    "name": "Cristian Pavon",
    "position": "EXD",
    "rating": 78,
    "team": "Gremio",
    "tier": "SILVER",
    "photoUrl": "",
    "age": 29,
  },
  {
    "name": "Exequiel Zeballos",
    "position": "EXD",
    "rating": 78,
    "team": "",
    "tier": "SILVER",
    "photoUrl": "",
    "age": 23,
  },
  {
    "name": "Lucas Janson",
    "position": "EXI",
    "rating": 77,
    "team": "",
    "tier": "SILVER",
    "photoUrl": "",
    "age": 31,
  },
  {
    "name": "Ian Subiabre",
    "position": "EXD",
    "rating": 74,
    "team": "River Plate",
    "tier": "SILVER",
    "photoUrl": "",
    "age": 18,
  },
  {
    "name": "Jude Bellingham",
    "position": "MO",
    "rating": 88,
    "team": "Real Madrid",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 22,
  },
  {
    "name": "Jamal Musiala",
    "position": "MO",
    "rating": 87,
    "team": "Bayer Munich",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 22,
  },
  {
    "name": "Martin Odegar",
    "position": "MO",
    "rating": 86,
    "team": "Arsenal FC",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 27,
  },
  {
    "name": "Cole Palmer",
    "position": "MO",
    "rating": 86,
    "team": "Chelsea",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 23,
  },
  {
    "name": "Florian Wirtz",
    "position": "MO",
    "rating": 86,
    "team": "Liverpool",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 22,
  },
  {
    "name": "Bernardo Silva",
    "position": "MO",
    "rating": 86,
    "team": "Manchester City",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 30,
  },
  {
    "name": "Kevin de Bruyne",
    "position": "MO",
    "rating": 86,
    "team": "Napoli",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 34,
  },
  {
    "name": "Eneriche Eze",
    "position": "MO",
    "rating": 84,
    "team": "Arsenal FC",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 27,
  },
  {
    "name": "Xavi Simons",
    "position": "MO",
    "rating": 84,
    "team": "Tottenham Hotspur",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 22,
  },
  {
    "name": "Dani Olmo",
    "position": "MO",
    "rating": 84,
    "team": "Barcelona",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 27,
  },
  {
    "name": "Lucas Paqueta",
    "position": "MO",
    "rating": 83,
    "team": "West Ham United",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 28,
  },
  {
    "name": "Isco",
    "position": "MO",
    "rating": 83,
    "team": "Real Betis",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 33,
  },
  {
    "name": "Fermin Lopez",
    "position": "MO",
    "rating": 82,
    "team": "Barcelona",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 21,
  },
  {
    "name": "Giovani Lo Celso",
    "position": "MO",
    "rating": 82,
    "team": "Real Betis",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 29,
  },
  {
    "name": "Thiago Almada",
    "position": "MO",
    "rating": 82,
    "team": "Atletico Madrid",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 24,
  },
  {
    "name": "Arda Guler",
    "position": "MO",
    "rating": 82,
    "team": "Real Madrid",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 20,
  },
  {
    "name": "Carlos Palacios",
    "position": "MO",
    "rating": 80,
    "team": "Boca Juniors",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 25,
  },
  {
    "name": "Fernando Quintero",
    "position": "MO",
    "rating": 80,
    "team": "River Plate",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 32,
  },
  {
    "name": "Pity Martinez",
    "position": "MO",
    "rating": 80,
    "team": "River Plate",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 32,
  },
  {
    "name": "Nacho Fernandez",
    "position": "MO",
    "rating": 78,
    "team": "River Plate",
    "tier": "SILVER",
    "photoUrl": "",
    "age": 35,
  },
  {
    "name": "Claudio Echeverri",
    "position": "MO",
    "rating": 78,
    "team": "Bayer Leverkusen",
    "tier": "SILVER",
    "photoUrl": "",
    "age": 19,
  },
  {
    "name": "Mamadou Sylla",
    "position": "CD",
    "rating": 77,
    "team": "Al Riyadh SC",
    "tier": "SILVER",
    "photoUrl": "",
    "age": 30,
  },
  {
    "name": "Pedri",
    "position": "MC",
    "rating": 87,
    "team": "Barcelona",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 23,
  },
  {
    "name": "Frenkie De Jong",
    "position": "MC",
    "rating": 86,
    "team": "Barcelona",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 28,
  },
  {
    "name": "Federico Valverde",
    "position": "MC",
    "rating": 86,
    "team": "Real Madrid",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 27,
  },
  {
    "name": "Vitinha",
    "position": "MC",
    "rating": 86,
    "team": "PSG",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 25,
  },
  {
    "name": "Alexis Mac Allister",
    "position": "MC",
    "rating": 85,
    "team": "Liverpool",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 27,
  },
  {
    "name": "Eduardo Camavinga",
    "position": "MC",
    "rating": 85,
    "team": "Real Madrid",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 23,
  },
  {
    "name": "Fabian Ruiz",
    "position": "MC",
    "rating": 85,
    "team": "PSG",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 29,
  },
  {
    "name": "Rodrigo de Paul",
    "position": "MC",
    "rating": 85,
    "team": "Inter Miami",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 31,
  },
  {
    "name": "Enzo Fernandez",
    "position": "MC",
    "rating": 84,
    "team": "Chelsea",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 24,
  },
  {
    "name": "Marcos Llorente",
    "position": "MC",
    "rating": 84,
    "team": "Atletico Madrid",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 30,
  },
  {
    "name": "Joao Neves",
    "position": "MC",
    "rating": 84,
    "team": "PSG",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 21,
  },
  {
    "name": "Adrien Rabiot",
    "position": "MC",
    "rating": 84,
    "team": "AC Milan",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 30,
  },
  {
    "name": "Luka Modric",
    "position": "MC",
    "rating": 83,
    "team": "AC Milan",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 40,
  },
  {
    "name": "Gavi",
    "position": "MC",
    "rating": 83,
    "team": "Barcelona",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 21,
  },
  {
    "name": "Paul Pogba",
    "position": "MC",
    "rating": 83,
    "team": "AC Monaco",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 32,
  },
  {
    "name": "Gundogan",
    "position": "MC",
    "rating": 83,
    "team": "Galatasaray SK",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 35,
  },
  {
    "name": "Ander Herrera",
    "position": "MC",
    "rating": 79,
    "team": "Boca Juniors",
    "tier": "SILVER",
    "photoUrl": "",
    "age": 36,
  },
  {
    "name": "Dani Parejo",
    "position": "MC",
    "rating": 82,
    "team": "Villarreal",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 36,
  },
  {
    "name": "Pierre Hojbjerfg",
    "position": "MC",
    "rating": 82,
    "team": "Olympique Lyonnais",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 30,
  },
  {
    "name": "Fredrik Aursnes",
    "position": "MC",
    "rating": 82,
    "team": "Benfica",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 30,
  },
  {
    "name": "Marcel Sabitzer",
    "position": "MC",
    "rating": 82,
    "team": "Borussia Dortmund",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 32,
  },
  {
    "name": "Pascal Grob",
    "position": "MC",
    "rating": 82,
    "team": "Borussia Dortmund",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 34,
  },
  {
    "name": "Zaver Schlager",
    "position": "MC",
    "rating": 82,
    "team": "RB Leipzig",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 27,
  },
  {
    "name": "Bitello",
    "position": "MC",
    "rating": 82,
    "team": "Dinamo Moskva",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 24,
  },
  {
    "name": "Orkun Kokcu",
    "position": "MC",
    "rating": 82,
    "team": "no se",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 30,
  },
  {
    "name": "Lovro Majer",
    "position": "MC",
    "rating": 80,
    "team": "Wolfsburg",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 27,
  },
  {
    "name": "RRiqui Puig",
    "position": "MC",
    "rating": 80,
    "team": "Los Angeles Galaxy",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 26,
  },
  {
    "name": "Charles Aranguiz",
    "position": "MC",
    "rating": 80,
    "team": "Universidad de Chile",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 35,
  },
  {
    "name": "Teddy",
    "position": "MC",
    "rating": 80,
    "team": "Stade de Reims",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 32,
  },
  {
    "name": "Gartano Castrovilli",
    "position": "MC",
    "rating": 80,
    "team": "SSC Bari",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 28,
  },
  {
    "name": "Nico Paz",
    "position": "MO",
    "rating": 78,
    "team": "Como 1907",
    "tier": "SILVER",
    "photoUrl": "",
    "age": 21,
  },
  {
    "name": "Rodri",
    "position": "MCD",
    "rating": 89,
    "team": "Manchester City",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 28,
  },
  {
    "name": "Declan Rise",
    "position": "MCD",
    "rating": 87,
    "team": "Arsenal FC",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 26,
  },
  {
    "name": "Joshua Kimmich",
    "position": "MCD",
    "rating": 87,
    "team": "Bayer Munich",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 30,
  },
  {
    "name": "Tchouameni",
    "position": "MCD",
    "rating": 86,
    "team": "Real Madrid",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 25,
  },
  {
    "name": "Zubimendi",
    "position": "MCD",
    "rating": 84,
    "team": "Arsenal FC",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 26,
  },
  {
    "name": "Moises Caicedo",
    "position": "MCD",
    "rating": 84,
    "team": "Chelsea",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 24,
  },
  {
    "name": "Manuel Locatelli",
    "position": "MCD",
    "rating": 83,
    "team": "Juvntus",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 27,
  },
  {
    "name": "Ngolo Kanté",
    "position": "MCD",
    "rating": 83,
    "team": "Al Ittihad Club",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 33,
  },
  {
    "name": "Casemiro",
    "position": "MCD",
    "rating": 82,
    "team": "Manchester United",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 33,
  },
  {
    "name": "Koke",
    "position": "MCD",
    "rating": 82,
    "team": "Atletico Madrid",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 33,
  },
  {
    "name": "Sergio Busquets",
    "position": "MCD",
    "rating": 82,
    "team": "Inter Miami",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 37,
  },
  {
    "name": "Leandro Paredes",
    "position": "MCD",
    "rating": 81,
    "team": "Boca Juniors",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 31,
  },
  {
    "name": "Milton Delgado",
    "position": "MCD",
    "rating": 76,
    "team": "Boca Juniors",
    "tier": "SILVER",
    "photoUrl": "",
    "age": 20,
  },
  {
    "name": "Enzo Perez",
    "position": "MCD",
    "rating": 79,
    "team": "River Plate",
    "tier": "Silver",
    "photoUrl": "",
    "age": 39,
  },
  {
    "name": "Kevin Kampl",
    "position": "MCD",
    "rating": 81,
    "team": "RB Leipzig",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 25,
  },
  {
    "name": "Maximilian Arnold",
    "position": "MCD",
    "rating": 81,
    "team": "Wolfsburg",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 25,
  },
  {
    "name": "Lucas Torreira",
    "position": "MCD",
    "rating": 81,
    "team": "Galatasaray SK",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 25,
  },
  {
    "name": "Thomas Delaney",
    "position": "MCD",
    "rating": 81,
    "team": "FC Kobenhavn",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 25,
  },
  {
    "name": "Tyler Adams",
    "position": "MDD",
    "rating": 80,
    "team": "Bournemouth",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 25,
  },
  {
    "name": "Vitaly Janelt",
    "position": "MCD",
    "rating": 80,
    "team": "Brentford",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 25,
  },
  {
    "name": "Florentino Luis",
    "position": "MCD",
    "rating": 80,
    "team": "El destructor",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 25,
  },
  {
    "name": "Jefferson Lerma",
    "position": "MCD",
    "rating": 80,
    "team": "Crystal Palance",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 25,
  },
  {
    "name": "Idrissa Gueye",
    "position": "MCD",
    "rating": 80,
    "team": "Everton",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 25,
  },
  {
    "name": "Ethan Ampadu",
    "position": "MCD",
    "rating": 80,
    "team": "Leeds United",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 25,
  },
  {
    "name": "Ryan Yates",
    "position": "MCD",
    "rating": 80,
    "team": "Nottingham Forest",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 25,
  },
  {
    "name": "Guido Rodriguez",
    "position": "MCD",
    "rating": 80,
    "team": "West Ham United",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 25,
  },
  {
    "name": "Ronaldo Mandragora",
    "position": "MCD",
    "rating": 80,
    "team": "Fiorentina",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 25,
  },
  {
    "name": "Ali Musrati",
    "position": "MCD",
    "rating": 80,
    "team": "Hellas Verona",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 25,
  },
  {
    "name": "Nicolo Rovella",
    "position": "MCD",
    "rating": 80,
    "team": "Lazio",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 25,
  },
  {
    "name": "Samuele Ricci",
    "position": "MCD",
    "rating": 80,
    "team": "AC Milan",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 25,
  },
  {
    "name": "Jobe Bellingham",
    "position": "MC",
    "rating": 78,
    "team": "Borussia Dortmund",
    "tier": "SILVER",
    "photoUrl": "",
    "age": 20,
  },
  {
    "name": "James Rodriguez",
    "position": "MO",
    "rating": 79,
    "team": "Algun equipo colombiano",
    "tier": "SILVER",
    "photoUrl": "",
    "age": 33,
  },
  {
    "name": "Theo Hernandez",
    "position": "LI",
    "rating": 85,
    "team": "Al Hilal",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 27,
  },
  {
    "name": "Nuno Mendes",
    "position": "LI",
    "rating": 84,
    "team": "PSG",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 23,
  },
  {
    "name": "Alphonso Davies",
    "position": "LI",
    "rating": 84,
    "team": "Bayer Munich",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 25,
  },
  {
    "name": "Riccardo Calafiori",
    "position": "LI",
    "rating": 83,
    "team": "Arsenal FC",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 23,
  },
  {
    "name": "Alejandro Balde",
    "position": "LI",
    "rating": 83,
    "team": "Barcelona",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 22,
  },
  {
    "name": "Estupiñan",
    "position": "LI",
    "rating": 82,
    "team": "AC Milan",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 27,
  },
  {
    "name": "Alvaro Carreras",
    "position": "LI",
    "rating": 82,
    "team": "Real Madrid",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 22,
  },
  {
    "name": "Marcos Acuña",
    "position": "LI",
    "rating": 82,
    "team": "River Plate",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 34,
  },
  {
    "name": "Jordi Alba",
    "position": "LI",
    "rating": 82,
    "team": "Inter Miami",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 36,
  },
  {
    "name": "Cucurella",
    "position": "LI",
    "rating": 81,
    "team": "Chelsea",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 27,
  },
  {
    "name": "Nicolas Tagliafico",
    "position": "LI",
    "rating": 80,
    "team": "Olympique Lyonnais",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 33,
  },
  {
    "name": "Ayrton Costa",
    "position": "LI",
    "rating": 79,
    "team": "Boca Juniors",
    "tier": "SILVER",
    "photoUrl": "",
    "age": 26,
  },
  {
    "name": "Valentin Barco",
    "position": "LI",
    "rating": 78,
    "team": "Racing de Strasbourg",
    "tier": "SILVER",
    "photoUrl": "",
    "age": 21,
  },
  {
    "name": "Milton Casco",
    "position": "LI",
    "rating": 78,
    "team": "River Plate",
    "tier": "SILVER",
    "photoUrl": "",
    "age": 37,
  },
  {
    "name": "Frank Fabra",
    "position": "LI",
    "rating": 78,
    "team": "Boca Juniors",
    "tier": "Silver",
    "photoUrl": "",
    "age": 34,
  },
  {
    "name": "Miguel Gutierrez",
    "position": "LI",
    "rating": 82,
    "team": "Napoli",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 25,
  },
  {
    "name": "Leonardo Spinazzola",
    "position": "LI",
    "rating": 82,
    "team": "Napoli",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 25,
  },
  {
    "name": "Sergi Cardona",
    "position": "LI",
    "rating": 82,
    "team": "Villarreal",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 25,
  },
  {
    "name": "Takehiro Tomiyasu",
    "position": "LI",
    "rating": 82,
    "team": "Libre",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 25,
  },
  {
    "name": "Reinaldo Mandava",
    "position": "LI",
    "rating": 81,
    "team": "Sunderland",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 25,
  },
  {
    "name": "Nuno Tavares",
    "position": "LI",
    "rating": 81,
    "team": "Lazio",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 25,
  },
  {
    "name": "Adam Marusic",
    "position": "LI",
    "rating": 81,
    "team": "Lazio",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 25,
  },
  {
    "name": "Carlos Augusto",
    "position": "LI",
    "rating": 81,
    "team": "Inter Milan",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 25,
  },
  {
    "name": "Mathias Oliveraa",
    "position": "LI",
    "rating": 81,
    "team": "Napoli",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 25,
  },
  {
    "name": "Javi Galan",
    "position": "LI",
    "rating": 81,
    "team": "Atletico Madrid",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 25,
  },
  {
    "name": "Fran Garcia",
    "position": "LI",
    "rating": 81,
    "team": "Real Madrid",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 25,
  },
  {
    "name": "Ferland Mendy",
    "position": "LI",
    "rating": 81,
    "team": "Real Madrid",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 25,
  },
  {
    "name": "Trent Alexander-Arnold",
    "position": "LD",
    "rating": 86,
    "team": "Real Madrid",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 27,
  },
  {
    "name": "Jurrien Timber",
    "position": "LD",
    "rating": 85,
    "team": "Arsenal FC",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 24,
  },
  {
    "name": "Jules Kounde",
    "position": "LD",
    "rating": 85,
    "team": "Barcelona",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 27,
  },
  {
    "name": "Hakimi",
    "position": "LD",
    "rating": 85,
    "team": "PSG",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 27,
  },
  {
    "name": "Joao Cancelo",
    "position": "LD",
    "rating": 84,
    "team": "Al Hilal",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 30,
  },
  {
    "name": "Kyle Walker",
    "position": "LD",
    "rating": 83,
    "team": "Burnley FC",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 35,
  },
  {
    "name": "Jeremie Frimpong",
    "position": "LD",
    "rating": 83,
    "team": "Liverpool",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 25,
  },
  {
    "name": "Nahuel Molina",
    "position": "LD",
    "rating": 83,
    "team": "Atletico Madrid",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 27,
  },
  {
    "name": "Daniel Carvajal",
    "position": "LD",
    "rating": 83,
    "team": "Real Madrid",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 33,
  },
  {
    "name": "Gonzalo Montiel",
    "position": "LD",
    "rating": 82,
    "team": "River Plate",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 28,
  },
  {
    "name": "Sacha Boey",
    "position": "LD",
    "rating": 81,
    "team": "Bayer Munich",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 25,
  },
  {
    "name": "Malo Gusto",
    "position": "LD",
    "rating": 80,
    "team": "Chelsea",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 22,
  },
  {
    "name": "Luis Advincula",
    "position": "LD",
    "rating": 79,
    "team": "Boca Juniors",
    "tier": "SILVER",
    "photoUrl": "",
    "age": 35,
  },
  {
    "name": "Lucas Blondel",
    "position": "LD",
    "rating": 78,
    "team": "Boca Juniors",
    "tier": "SILVER",
    "photoUrl": "",
    "age": 29,
  },
  {
    "name": "Danilo Luiz",
    "position": "LD",
    "rating": 81,
    "team": "Flamengo",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 25,
  },
  {
    "name": "Julian Ryerson",
    "position": "LD",
    "rating": 81,
    "team": "Borussia Dortmund",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 25,
  },
  {
    "name": "Davide Calabria",
    "position": "LD",
    "rating": 81,
    "team": "Panathinaikos",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 25,
  },
  {
    "name": "Matty Cash",
    "position": "LD",
    "rating": 81,
    "team": "Aston Villa",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 25,
  },
  {
    "name": "Diogo Dalot",
    "position": "LD",
    "rating": 81,
    "team": "Manchester United",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 25,
  },
  {
    "name": "Tino Livramento",
    "position": "LD",
    "rating": 81,
    "team": "NewCastle United",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 25,
  },
  {
    "name": "Kieran Trippier",
    "position": "LD",
    "rating": 81,
    "team": "Newcastle United",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 25,
  },
  {
    "name": "Nordi Mukiele",
    "position": "LD",
    "rating": 81,
    "team": "Sunderland",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 25,
  },
  {
    "name": "Djed Spence",
    "position": "LD",
    "rating": 81,
    "team": "Tottenham Hotspur",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 25,
  },
  {
    "name": "Wesley Franca",
    "position": "LD",
    "rating": 81,
    "team": "AS Roma",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 25,
  },
  {
    "name": "Virgil van Dijk",
    "position": "DEC",
    "rating": 88,
    "team": "Liverpool",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 34,
  },
  {
    "name": "William Saliba",
    "position": "DEC",
    "rating": 87,
    "team": "Arsenal FC",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 24,
  },
  {
    "name": "Ruben Dias",
    "position": "DEC",
    "rating": 86,
    "team": "Manchester City",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 27,
  },
  {
    "name": "Ronald Araujo",
    "position": "DEC",
    "rating": 85,
    "team": "Barcelona",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 26,
  },
  {
    "name": "Eder Militao",
    "position": "DEC",
    "rating": 85,
    "team": "Real Madrid",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 27,
  },
  {
    "name": "Konate",
    "position": "DEC",
    "rating": 84,
    "team": "Liverpool",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 26,
  },
  {
    "name": "Cuti Romero",
    "position": "DEC",
    "rating": 84,
    "team": "Tottenham Hotspur",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 27,
  },
  {
    "name": "Dean Huijsen",
    "position": "DEC",
    "rating": 84,
    "team": "Real Madrid",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 20,
  },
  {
    "name": "Willian Pacho",
    "position": "DEC",
    "rating": 84,
    "team": "PSG",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 24,
  },
  {
    "name": "Kim Min-Jae",
    "position": "DEC",
    "rating": 84,
    "team": "Bayer Munich",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 29,
  },
  {
    "name": "Lisandro Martinez",
    "position": "DEC",
    "rating": 83,
    "team": "Manchester United",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 27,
  },
  {
    "name": "Bremer",
    "position": "DEC",
    "rating": 83,
    "team": "Juventus",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 28,
  },
  {
    "name": "Pau Cubarsi",
    "position": "DEC",
    "rating": 83,
    "team": "Barcelona",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 18,
  },
  {
    "name": "Christiansen",
    "position": "DEC",
    "rating": 82,
    "team": "Barcelona",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 29,
  },
  {
    "name": "Alaba",
    "position": "DEC",
    "rating": 82,
    "team": "Real Madrid",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 33,
  },
  {
    "name": "Nicolas Otamendi",
    "position": "DEC",
    "rating": 82,
    "team": "Benfica",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 37,
  },
  {
    "name": "Marcos Rojo",
    "position": "DEC",
    "rating": 79,
    "team": "Racing",
    "tier": "SILVER",
    "photoUrl": "",
    "age": 79,
  },
  {
    "name": "Mercado",
    "position": "DEC",
    "rating": 78,
    "team": "SC Internacional",
    "tier": "SILVER",
    "photoUrl": "",
    "age": 38,
  },
  {
    "name": "Jorge Figal",
    "position": "DEC",
    "rating": 77,
    "team": "Boca Juniors",
    "tier": "SILVER",
    "photoUrl": "",
    "age": 31,
  },
  {
    "name": "Lucas Hernandez",
    "position": "DEC",
    "rating": 83,
    "team": "PSG",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 25,
  },
  {
    "name": "Edmond Tapsoba",
    "position": "DEC",
    "rating": 83,
    "team": "Bayer Leverkusen",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 25,
  },
  {
    "name": "Matthias Ginter",
    "position": "DEC",
    "rating": 83,
    "team": "Freiburg",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 25,
  },
  {
    "name": "Aymeric Laporte",
    "position": "DEC",
    "rating": 83,
    "team": "Al Nassr",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 25,
  },
  {
    "name": "Azri Konsa",
    "position": "DEC",
    "rating": 82,
    "team": "Aston Villa",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 25,
  },
  {
    "name": "Pau Torres",
    "position": "DEC",
    "rating": 82,
    "team": "Aston Villa",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 25,
  },
  {
    "name": "Marc Gueehi",
    "position": "DEC",
    "rating": 82,
    "team": "Crystal Palace",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 25,
  },
  {
    "name": "Joachim Andersen",
    "position": "DEC",
    "rating": 82,
    "team": "Fulham",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 25,
  },
  {
    "name": "Matthijss de Ligt",
    "position": "DEC",
    "rating": 82,
    "team": "Manchester United",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 25,
  },
  {
    "name": "Harry Maguire",
    "position": "DEC",
    "rating": 82,
    "team": "Manchester United",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 25,
  },
  {
    "name": "Sven Botman",
    "position": "DEC",
    "rating": 82,
    "team": "Newcastle United",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 25,
  },
  {
    "name": "Malick Thiaw",
    "position": "DEC",
    "rating": 82,
    "team": "Newcastle United",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 25,
  },
  {
    "name": "Fabian Schar",
    "position": "DEC",
    "rating": 82,
    "team": "",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 25,
  },
  {
    "name": "Mueillo",
    "position": "DEC",
    "rating": 82,
    "team": "Nottingham Forest",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 25,
  },
  {
    "name": "Nikola Milenkovic",
    "position": "DEC",
    "rating": 82,
    "team": "Nottingham Forest",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 25,
  },
  {
    "name": "Kevin Danso",
    "position": "DEC",
    "rating": 82,
    "team": "Tottenham Hotspur",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 25,
  },
  {
    "name": "Giorgio Scalvini",
    "position": "DEC",
    "rating": 82,
    "team": "Atalanta",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 25,
  },
  {
    "name": "Pierre Kalulu",
    "position": "DEC",
    "rating": 82,
    "team": "Juventus",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 25,
  },
  {
    "name": "Alessio Romangnoli",
    "position": "DEC",
    "rating": 82,
    "team": "Lazio",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 25,
  },
  {
    "name": "Buongiorno",
    "position": "DEC",
    "rating": 82,
    "team": "Napoli",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 25,
  },
  {
    "name": "Amir Reahmani",
    "position": "DEC",
    "rating": 82,
    "team": "Napoli",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 25,
  },
  {
    "name": "Evan Ndicka",
    "position": "DEC",
    "rating": 82,
    "team": "AS Roma",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 25,
  },
  {
    "name": "Gianluca Manchini",
    "position": "DEC",
    "rating": 82,
    "team": "AS Roma",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 25,
  },
  {
    "name": "Mario Hermoso",
    "position": "DEC",
    "rating": 82,
    "team": "AS Roma",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 25,
  },
  {
    "name": "Aitor Paredes",
    "position": "DEC",
    "rating": 82,
    "team": "Athleric Bilbao",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 25,
  },
  {
    "name": "Arthur Theate",
    "position": "DEC",
    "rating": 82,
    "team": "Eintracht Frankfurt",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 25,
  },
  {
    "name": "Philipp Lienhart",
    "position": "DEC",
    "rating": 82,
    "team": "Freiburg",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 25,
  },
  {
    "name": "Willi Orban",
    "position": "DEC",
    "rating": 82,
    "team": "Leipzing",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 25,
  },
  {
    "name": "Milan Skriniar",
    "position": "DEC",
    "rating": 82,
    "team": "Fenerbhance",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 25,
  },
  {
    "name": "Roger Ibañez",
    "position": "DEC",
    "rating": 82,
    "team": "Al Ahli",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 25,
  },
  {
    "name": "Curtois",
    "position": "PO",
    "rating": 87,
    "team": "Real Madrid",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 33,
  },
  {
    "name": "Jan Oblak",
    "position": "PO",
    "rating": 86,
    "team": "Atletico Madrid",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 32,
  },
  {
    "name": "Manuel Neuer",
    "position": "PO",
    "rating": 86,
    "team": "Bayer Munich",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 39,
  },
  {
    "name": "Dibu Martinez",
    "position": "PO",
    "rating": 85,
    "team": "Aston Villa",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 33,
  },
  {
    "name": "Alisson Becker",
    "position": "PO",
    "rating": 85,
    "team": "Liverpool",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 33,
  },
  {
    "name": "Donnarumma",
    "position": "PO",
    "rating": 85,
    "team": "Manchester City",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 25,
  },
  {
    "name": "Ter Stegen",
    "position": "PO",
    "rating": 85,
    "team": "Barcelona",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 33,
  },
  {
    "name": "De Gea",
    "position": "PO",
    "rating": 84,
    "team": "Fiorentina",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 35,
  },
  {
    "name": "Joan Garcia",
    "position": "PO",
    "rating": 83,
    "team": "Barcelona",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 24,
  },
  {
    "name": "Szczesny",
    "position": "PO",
    "rating": 83,
    "team": "Barcelona",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 35,
  },
  {
    "name": "Lunin",
    "position": "PO",
    "rating": 82,
    "team": "Real Madrid",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 26,
  },
  {
    "name": "Batalla",
    "position": "PO",
    "rating": 81,
    "team": "Rayo Vallecano",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 29,
  },
  {
    "name": "Rulli",
    "position": "PO",
    "rating": 81,
    "team": "Olympique Marseille",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 33,
  },
  {
    "name": "Juan Musso",
    "position": "PO",
    "rating": 80,
    "team": "Atletico Madrid",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 31,
  },
  {
    "name": "Armani",
    "position": "PO",
    "rating": 81,
    "team": "River Plate",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 39,
  },
  {
    "name": "Sergio Romero",
    "position": "PO",
    "rating": 78,
    "team": "Boca Juniors",
    "tier": "SILVER",
    "photoUrl": "",
    "age": 38,
  },
  {
    "name": "Centurion",
    "position": "PO",
    "rating": 78,
    "team": "Independiente Rivadavia",
    "tier": "SILVER",
    "photoUrl": "",
    "age": 28,
  },
  {
    "name": "Marchesin",
    "position": "PO",
    "rating": 79,
    "team": "Boca Juniors",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 37,
  },
  {
    "name": "Jordan Pickford",
    "position": "PO",
    "rating": 84,
    "team": "Everton",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 31,
  },
  {
    "name": "Paulo Gazzaniga",
    "position": "PO",
    "rating": 81,
    "team": "Girona",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 25,
  },
  {
    "name": "Sergio Herrera",
    "position": "PO",
    "rating": 81,
    "team": "Osasuna",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 25,
  },
  {
    "name": "Kevin Trapp",
    "position": "PO",
    "rating": 81,
    "team": "Paris FC",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 25,
  },
  {
    "name": "Fabio Maciel",
    "position": "PO",
    "rating": 81,
    "team": "Fluminense",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 25,
  },
  {
    "name": "Weverton Pereira",
    "position": "PO",
    "rating": 81,
    "team": "Palmeiras",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 25,
  },
  {
    "name": "Mark Plekken",
    "position": "PO",
    "rating": 81,
    "team": "Bayer Leverkusen",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 25,
  },
  {
    "name": "Yann Sommer",
    "position": "PO",
    "rating": 85,
    "team": "Inter Milan",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 25,
  },
  {
    "name": "Ruben Rubio",
    "position": "PO",
    "rating": 86,
    "team": "Cadiz",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 25,
  },
  {
    "name": "David Raya",
    "position": "PO",
    "rating": 85,
    "team": "Arsenal",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 25,
  },

  {
    "name": "Kevin Volland",
    "position": "CD",
    "rating": 82,
    "team": "sin tim",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 32,
  },
  {
    "name": "Danny Wlbeck",
    "position": "CD",
    "rating": 81,
    "team": "Brigthon",
    "tier": "GOLD",
    "photoUrl": "",
    "age": 35,
  },



  // ... COPIA Y PEGA MÁS JUGADORES AQUÍ ...
];

// Esta es la función que hace la magia
Future<void> uploadPlayersToFirestore() async {
  final CollectionReference playersRef = FirebaseFirestore.instance.collection('players');

  print("--- INICIANDO CARGA DE JUGADORES ---");

  for (var player in initialPlayers) {
    // Usamos el nombre como ID del documento para evitar duplicados
    // (Ej: si subes a Messi dos veces, solo se actualiza, no se crea otro)
    String docId = player['name'].toString().toLowerCase().replaceAll(' ', '_');

    try {
      await playersRef.doc(docId).set(player);
      print("Subido: ${player['name']}");
    } catch (e) {
      print("Error subiendo a ${player['name']}: $e");
    }
  }

  print("--- CARGA FINALIZADA CON ÉXITO ---");
}