// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxcsCvW6vSRSffRJ3iYNKIydsQW-XYjyE',
    appId: '1:766699560434:web:7085461740eff753f99f6b',
    messagingSenderId: '766699560434',
    projectId: 'pes-league-manager-v2',
    authDomain: 'pes-league-manager-v2.firebaseapp.com',
    storageBucket: 'pes-league-manager-v2.firebasestorage.app',
    measurementId: 'G-YB7E1H8TS7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvXUwSQWExaqJAeRZ3FQvT6QHA_qKu1Is',
    appId: '1:766699560434:android:228da9d825c3781ff99f6b',
    messagingSenderId: '766699560434',
    projectId: 'pes-league-manager-v2',
    storageBucket: 'pes-league-manager-v2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBy5Fv5-OcmDKjcsrdoDfk21Ol8sZ20CZY',
    appId: '1:766699560434:ios:64a3d5c640f00301f99f6b',
    messagingSenderId: '766699560434',
    projectId: 'pes-league-manager-v2',
    storageBucket: 'pes-league-manager-v2.firebasestorage.app',
    iosBundleId: 'com.tuliga.pesLeagueManager',
  );
}
