// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaxk0MEuyog-l9tZWSceAdXKacxjPjdow',
    appId: '1:501939973190:web:d5174f926c1f023eedae47',
    messagingSenderId: '501939973190',
    projectId: 'pes-league-manager-juan-99414',
    authDomain: 'pes-league-manager-juan-99414.firebaseapp.com',
    storageBucket: 'pes-league-manager-juan-99414.firebasestorage.app',
    measurementId: 'G-ENSGQY8K4X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1isLMnVy9c9fo-VcoezhS9BDnciJ-42I',
    appId: '1:501939973190:android:aee3db6a950ec902edae47',
    messagingSenderId: '501939973190',
    projectId: 'pes-league-manager-juan-99414',
    storageBucket: 'pes-league-manager-juan-99414.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUBIeTveeaXeES6XbPG0XYDZtkgUNMKW0',
    appId: '1:501939973190:ios:1a1fe169f6993dcbedae47',
    messagingSenderId: '501939973190',
    projectId: 'pes-league-manager-juan-99414',
    storageBucket: 'pes-league-manager-juan-99414.firebasestorage.app',
    iosBundleId: 'com.tuliga.pesLeagueManager',
  );

}